# Generated by Django 4.1.7 on 2023-03-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(max_length=10)),
                ('created_date', models.DateField()),
                ('created_time', models.TimeField()),
            ],
        ),
    ]
