# Generated by Django 4.1.7 on 2023-02-24 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_timestamp',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user_timestamp',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='user_timestamp',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 2, 24)),
        ),
        migrations.AddField(
            model_name='user_timestamp',
            name='created_time',
            field=models.TimeField(default=datetime.time(16, 48, 49, 88491)),
        ),
    ]
