# Generated by Django 3.2.17 on 2023-02-26 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_app', '0002_remove_user_timestamp_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_timestamp',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 2, 26)),
        ),
        migrations.AlterField(
            model_name='user_timestamp',
            name='created_time',
            field=models.TimeField(default=datetime.time(13, 2, 57, 392539)),
        ),
    ]
