# Generated by Django 3.2.9 on 2023-02-26 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_app', '0003_auto_20230226_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_timestamp',
            name='created_time',
            field=models.TimeField(default=datetime.time(15, 49, 56, 852308)),
        ),
    ]
