version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - pfenetwork
  timestamp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/timestamp
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - pfenetwork
  adminer:
    image: adminer
    ports:
      - 8089:8080
    restart: unless-stopped
    networks:
      - pfenetwork

networks:
  pfenetwork:
    driver: bridge
